-- Replace only the technical names generated by the previous admin creation flow.
-- Preserve IDs, custom names, and creation order within each client's environment.
DO $$
DECLARE
  item record;
  base_label text;
  label_number integer;
  candidate text;
BEGIN
  FOR item IN
    SELECT id, client_id, environment, created_at
    FROM deployments
    WHERE name ~* ('-' || environment || '-(niq|client-cloud)-[0-9a-f]{8}$')
    ORDER BY client_id, environment, created_at, id
  LOOP
    base_label := upper(left(item.environment, 1)) || substring(item.environment from 2);
    SELECT count(*) + 1 INTO label_number
    FROM deployments sibling
    WHERE sibling.client_id = item.client_id
      AND sibling.environment = item.environment
      AND (sibling.created_at, sibling.id) < (item.created_at, item.id);
    candidate := CASE WHEN label_number = 1 THEN base_label ELSE base_label || ' ' || label_number END;
    WHILE EXISTS (
      SELECT 1 FROM deployments sibling
      WHERE sibling.client_id = item.client_id
        AND sibling.id <> item.id
        AND lower(btrim(sibling.name)) = lower(candidate)
    ) LOOP
      label_number := label_number + 1;
      candidate := base_label || ' ' || label_number;
    END LOOP;
    UPDATE deployments SET name = candidate, updated_at = now() WHERE id = item.id;
  END LOOP;
END $$;
