import type { RuleDefinition } from '@niq-scoring/contracts/rules';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { ConditionEditor } from './ConditionEditor';
import { newRuleId } from './questionnaire-model';
import { ScoringField, ScoringNumber, ScoringSelect } from './scoring-controls';
import { scoringReferences } from './scoring-model';
type Props={definition:RuleDefinition;onChange:(definition:RuleDefinition)=>void;disabled?:boolean};
export function InterventionEditor({definition:d,onChange,disabled=false}:Props) {
  const update=(index:number,changes:Partial<RuleDefinition['interventions'][number]>)=>onChange({...d,interventions:d.interventions.map((item,i)=>i===index?{...item,...changes}:item)});
  return <fieldset disabled={disabled} className="space-y-5 min-w-0"><div><h3 className="text-lg font-medium">Interventions</h3><p className="mt-2 text-sm text-muted-foreground">Add guidance supported by your source material. Conditions decide when it appears. Higher priority appears first; only the highest-priority match in an exclusive group is returned.</p></div>{d.interventions.map((item,index)=>{const uses=scoringReferences(d,'intervention',item.id);return <section key={item.id} className="space-y-4 rounded-lg border p-4"><div className="grid gap-3 sm:grid-cols-2"><ScoringField label="Intervention name"><Input aria-label="Intervention name" value={item.label} onChange={e=>update(index,{label:e.target.value})}/></ScoringField><ScoringSelect label="Guidance type" value={item.kind} options={[{value:'goal',label:'Goal'},{value:'recommendation',label:'Recommendation'},{value:'care_tier',label:'Care tier'},{value:'monitoring',label:'Monitoring'},{value:'note',label:'Note'}]} onChange={kind=>update(index,{kind:kind as typeof item.kind})}/></div><ScoringField label="Guidance"><textarea aria-label="Guidance" rows={3} className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={item.text} onChange={e=>update(index,{text:e.target.value})}/></ScoringField><ConditionEditor definition={d} value={item.when} required disabled={disabled} onChange={when=>{if(when)update(index,{when})}}/><div className="grid gap-3 sm:grid-cols-2"><ScoringNumber label="Priority (0–10000)" min={0} max={10000} value={item.priority} onChange={priority=>update(index,{priority:priority??0})}/><ScoringField label="Exclusive group (optional)"><Input aria-label="Exclusive group (optional)" placeholder="e.g. care_tier" value={item.exclusiveGroup??''} onChange={e=>update(index,{exclusiveGroup:e.target.value||null})}/></ScoringField></div><Button type="button" variant="outline" disabled={uses.length>0} onClick={()=>onChange({...d,interventions:d.interventions.filter((_,i)=>i!==index)})}>Remove intervention</Button>{uses.length>0&&<p className="text-sm text-muted-foreground">Used by {uses.join(', ')}. Remove these expectations first.</p>}</section>})}<Button type="button" variant="outline" onClick={()=>onChange({...d,interventions:[...d.interventions,{id:newRuleId('intervention'),label:'New intervention',kind:'recommendation',text:'',priority:0,exclusiveGroup:null,when:{match:'all',tests:[{ref:{kind:'total',id:'total'},operator:'answered'}]},sources:[]}]})}>Add intervention</Button></fieldset>;
}
