import type { RuleDefinition } from '@niq-scoring/contracts/rules';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { ConditionEditor } from './ConditionEditor';
import { newRuleId } from './questionnaire-model';
import { ScoringField, ScoringNumber, ScoringSelect, RangeFields } from './scoring-controls';
import { optionPoints, scoringReferences, synchronizeOptionPoints } from './scoring-model';
type Props = {definition:RuleDefinition;onChange:(definition:RuleDefinition)=>void;disabled?:boolean};
type Score = RuleDefinition['scoring'][number];
const aggregation = [{value:'sum',label:'Sum'},{value:'max',label:'Highest value'}];
export function ScoringEditor({definition:d,onChange,disabled=false}:Props) {
  const questions=d.sections.flatMap(section=>section.questions);
  const numeric=[...questions.filter(q=>q.type==='number').map(q=>({value:`question:${q.id}`,label:q.label})),...d.calculations.map(c=>({value:`calculation:${c.id}`,label:c.label}))];
  const optionQuestions=questions.filter(q=>q.type==='single_select'||q.type==='multi_select');
  const patch=(index:number,value:Score)=>onChange({...d,scoring:d.scoring.map((rule,i)=>i===index?value:rule)});
  function add(kind:Score['kind']) {
    const base={id:newRuleId('score'),label:'New scoring rule',domainId:d.domains[0]!.id,sources:[]};
    const rule:Score=kind==='options'?{...base,kind,questionId:optionQuestions[0]!.id,points:optionPoints(d,optionQuestions[0]!.id),aggregation:'sum',cap:null}:kind==='ranges'?{...base,kind,input:{kind:numeric[0]!.value.split(':')[0] as 'question'|'calculation',id:numeric[0]!.value.split(':')[1]!},bands:[{id:newRuleId('band'),min:null,max:null,minInclusive:true,maxInclusive:true,points:0}]}:{...base,kind,when:{match:'all',tests:[{ref:{kind:'question',id:questions[0]!.id},operator:'answered'}]},points:0,otherwise:0};
    onChange({...d,scoring:[...d.scoring,rule]});
  }
  return <fieldset disabled={disabled} className="space-y-8 min-w-0">
    <section className="space-y-4"><h3 className="text-lg font-medium">Domains</h3><p className="text-sm text-muted-foreground">Group component scores. Leave a cap blank for no upper limit.</p>{d.domains.map((domain,index)=>{const uses=scoringReferences(d,'domain',domain.id);return <div key={domain.id} className="space-y-3 rounded-lg border p-4"><div className="grid gap-3 sm:grid-cols-2"><ScoringField label="Domain name"><Input aria-label="Domain name" value={domain.label} onChange={e=>onChange({...d,domains:d.domains.map((v,i)=>i===index?{...v,label:e.target.value}:v)})}/></ScoringField><ScoringNumber label="Domain cap" min={0} value={domain.cap} onChange={cap=>onChange({...d,domains:d.domains.map((v,i)=>i===index?{...v,cap}:v)})}/></div><Button type="button" variant="outline" disabled={uses.length>0} onClick={()=>onChange({...d,domains:d.domains.filter((_,i)=>i!==index)})}>Remove domain</Button>{uses.length>0&&<p className="text-sm text-muted-foreground">Used by {uses.join(', ')}. Remove these references first.</p>}</div>})}<Button type="button" variant="outline" onClick={()=>onChange({...d,domains:[...d.domains,{id:newRuleId('domain'),label:'New domain',cap:null,sources:[]}]})}>Add domain</Button></section>
    <section className="space-y-4"><h3 className="text-lg font-medium">Scoring rules</h3>{!d.domains.length&&<p className="text-sm text-muted-foreground">Add a domain before adding scoring rules.</p>}{d.scoring.map((rule,index)=><div key={rule.id} className="space-y-4 rounded-lg border p-4"><div className="grid gap-3 sm:grid-cols-2"><ScoringField label="Rule name"><Input aria-label="Rule name" value={rule.label} onChange={e=>patch(index,{...rule,label:e.target.value})}/></ScoringField><ScoringSelect label="Domain" value={rule.domainId} options={d.domains.map(v=>({value:v.id,label:v.label}))} onChange={domainId=>patch(index,{...rule,domainId})}/></div>
      {rule.kind==='options'&&<><ScoringSelect label="Question" value={rule.questionId} options={optionQuestions.map(q=>({value:q.id,label:q.label}))} onChange={questionId=>patch(index,{...rule,questionId,points:optionPoints(d,questionId)})}/><p className="text-sm text-muted-foreground">Changing the question resets its option points. After editing answer options, synchronize the mapping to include new options at zero points.</p><Button type="button" variant="outline" onClick={()=>patch(index,{...rule,points:synchronizeOptionPoints(d,rule)})}>Synchronize answer options</Button>{rule.points.map((point,i)=><ScoringNumber key={point.optionId} label={questions.find(q=>q.id===rule.questionId)?.options.find(o=>o.id===point.optionId)?.label??`Missing option: ${point.optionId}`} value={point.points} onChange={points=>patch(index,{...rule,points:rule.points.map((p,j)=>i===j?{...p,points:points??0}:p)})}/>)}<div className="grid gap-3 sm:grid-cols-2"><ScoringSelect label="Combine selected options" value={rule.aggregation} options={aggregation} onChange={value=>patch(index,{...rule,aggregation:value as 'sum'|'max'})}/><ScoringNumber label="Component cap" min={0} value={rule.cap} onChange={cap=>patch(index,{...rule,cap})}/></div></>}
      {rule.kind==='ranges'&&<><ScoringSelect label="Numeric input" value={`${rule.input.kind}:${rule.input.id}`} options={numeric} onChange={value=>{const[kind,id]=value.split(':');patch(index,{...rule,input:{kind:kind as 'question'|'calculation',id:id!}})}}/>{rule.bands.map((band,i)=><div key={band.id} className="space-y-3 rounded-md bg-muted/30 p-3"><RangeFields value={band} onChange={value=>patch(index,{...rule,bands:rule.bands.map((b,j)=>i===j?{...b,...value}:b)})}/><ScoringNumber label="Range points" value={band.points} onChange={points=>patch(index,{...rule,bands:rule.bands.map((b,j)=>i===j?{...b,points:points??0}:b)})}/><Button type="button" variant="outline" disabled={rule.bands.length===1} onClick={()=>patch(index,{...rule,bands:rule.bands.filter((_,j)=>i!==j)})}>Remove range</Button></div>)}<Button type="button" variant="outline" onClick={()=>patch(index,{...rule,bands:[...rule.bands,{id:newRuleId('band'),min:null,max:null,minInclusive:true,maxInclusive:true,points:0}]})}>Add range</Button></>}
      {rule.kind==='condition'&&<><ConditionEditor definition={d} value={rule.when} required disabled={disabled} allowedKinds={['question','calculation']} onChange={when=>{if(when)patch(index,{...rule,when})}}/><div className="grid gap-3 sm:grid-cols-2"><ScoringNumber label="Points when matched" value={rule.points} onChange={points=>patch(index,{...rule,points:points??0})}/><ScoringNumber label="Points otherwise" value={rule.otherwise} onChange={otherwise=>patch(index,{...rule,otherwise:otherwise??0})}/></div></>}
      <Button type="button" variant="outline" onClick={()=>onChange({...d,scoring:d.scoring.filter((_,i)=>i!==index)})}>Remove scoring rule</Button></div>)}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={!d.domains.length||!optionQuestions.length} onClick={()=>add('options')}>Add option scoring</Button><Button type="button" variant="outline" disabled={!d.domains.length||!numeric.length} onClick={()=>add('ranges')}>Add range scoring</Button><Button type="button" variant="outline" disabled={!d.domains.length||!questions.length} onClick={()=>add('condition')}>Add conditional scoring</Button></div></section>
    <section className="space-y-4"><h3 className="text-lg font-medium">Total score</h3><div className="grid gap-3 sm:grid-cols-3"><ScoringSelect label="Combine domains" value={d.total.aggregation} options={aggregation} onChange={value=>onChange({...d,total:{...d.total,aggregation:value as 'sum'|'max'}})}/><ScoringNumber label="Total cap" min={0} value={d.total.cap} onChange={cap=>onChange({...d,total:{...d.total,cap}})}/><ScoringNumber label="Decimal places (0–6)" min={0} max={6} value={d.total.precision} onChange={precision=>onChange({...d,total:{...d.total,precision:precision??0}})}/></div></section>
    <section className="space-y-4"><h3 className="text-lg font-medium">Classifications</h3><p className="text-sm text-muted-foreground">Define non-overlapping ranges covering every possible total score.</p>{d.classifications.map((item,index)=>{const uses=scoringReferences(d,'classification',item.id);return <div key={item.id} className="space-y-3 rounded-lg border p-4"><ScoringField label="Classification name"><Input aria-label="Classification name" value={item.label} onChange={e=>onChange({...d,classifications:d.classifications.map((v,i)=>i===index?{...v,label:e.target.value}:v)})}/></ScoringField><RangeFields value={item} onChange={value=>onChange({...d,classifications:d.classifications.map((v,i)=>i===index?{...v,...value}:v)})}/><ScoringField label="Interpretation"><Input aria-label="Interpretation" value={item.interpretation} onChange={e=>onChange({...d,classifications:d.classifications.map((v,i)=>i===index?{...v,interpretation:e.target.value}:v)})}/></ScoringField><Button type="button" variant="outline" disabled={uses.length>0} onClick={()=>onChange({...d,classifications:d.classifications.filter((_,i)=>i!==index)})}>Remove classification</Button>{uses.length>0&&<p className="text-sm text-muted-foreground">Used by {uses.join(', ')}. Remove these references first.</p>}</div>})}<Button type="button" variant="outline" onClick={()=>onChange({...d,classifications:[...d.classifications,{id:newRuleId('classification'),label:'New classification',interpretation:'',min:null,max:null,minInclusive:true,maxInclusive:true,sources:[]}]})}>Add classification</Button></section>
  </fieldset>;
}
